name: Fix Sonar Issues with Pixeebot
on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - uses: pixee/upload-tool-results-action@v1
      with:
          tool: sonar
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-component-key: owner_repo
          sonar-api-url: https://sonarcloud.io/api    
