name: Build Sonarcloude Analysis

on:
  push:
    branches:
      - release-5.0.0-pixee
        
jobs:
  sonarqube_analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sonarcloud Scanner
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=sbdjp_lms-service -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
